import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            colors: {
                'on-error-container': '#ffb2b9',
                'error-dim': '#d73357',
                'surface-container-lowest': '#000000',
                'on-tertiary': '#5e5f5f',
                'primary-dim': '#dc3300',
                'on-background': '#ffffff',
                'error': '#ff6e84',
                'tertiary': '#f9f9f9',
                'on-secondary-container': '#fff6f1',
                'surface-container-high': '#201f1f',
                'inverse-on-surface': '#565555',
                'background': '#0e0e0e',
                'surface-tint': '#ff8f73',
                'surface-variant': '#262626',
                'outline-variant': '#484847',
                'secondary-container': '#8e4e00',
                'primary-fixed': '#ff7856',
                'tertiary-fixed-dim': '#f1f1f1',
                'on-primary-fixed': '#000000',
                'on-tertiary-container': '#555757',
                'inverse-primary': '#b52900',
                'primary-container': '#ff7856',
                'on-secondary-fixed': '#512a00',
                'inverse-surface': '#fcf9f8',
                'tertiary-fixed': '#ffffff',
                'secondary': '#fd9000',
                'secondary-dim': '#ea8400',
                'secondary-fixed': '#ffc697',
                'on-error': '#490013',
                'surface-container-low': '#131313',
                'on-tertiary-fixed': '#4f5051',
                'surface-dim': '#0e0e0e',
                'secondary-fixed-dim': '#ffb470',
                'on-primary-container': '#490b00',
                'outline': '#767575',
                'on-surface-variant': '#adaaaa',
                'on-primary-fixed-variant': '#5a0f00',
                'on-secondary-fixed-variant': '#7a4300',
                'primary': '#ff8f73',
                'surface': '#0e0e0e',
                'surface-bright': '#2c2c2c',
                'on-tertiary-fixed-variant': '#6c6d6d',
                'on-surface': '#ffffff',
                'surface-container': '#1a1919',
                'on-secondary': '#462400',
                'tertiary-dim': '#ebebeb',
                'tertiary-container': '#ebebeb',
                'primary-fixed-dim': '#ff5c34',
                'error-container': '#a70138',
                'on-primary': '#5e1000',
                'surface-container-highest': '#262626',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                label: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
        },
    },

    plugins: [forms],
};
